config/routes.rb
require 'sidekiq/web'
ProjectLimelight::Application.routes.draw do

  get 'switch_user', :controller => 'switch_user', :action => 'set_current_user'

  scope 'api' do
    scope 'users' do
      scope 'follows' do
        post '' => 'follows#create', :type => 'User'
        delete '' => 'follows#destroy', :type => 'User'
      end
      scope 'stubs' do
        post '' => 'users#create_stub'
      end

      post 'invite_by_email' => 'users#invite_by_email'
      get 'index' => 'users#index'
      get 'notifications' => 'users#notifications'
      get 'following_users' => 'users#following_users'
      get 'following_topics' => 'users#following_topics'
      get 'followers' => 'users#followers'
      get 'influence_increases' => 'users#user_influence_increases'
      get 'influencer_topics' => 'users#influencer_topics'
      get 'almost_influencer_topics' => 'users#almost_influencer_topics'
      get ':id/topic_activity' => 'users#topic_activity'
      get ':id/topics/:topic_id/children' => 'users#topic_children'
      get ':id/topics/:topic_id/parents' => 'users#topic_parents'
      get ':id/topics' => 'users#topics'
      put ':id/networks' => 'users#update_network'
      post '' => 'users#create'
      put '' => 'users#update'
      get ':id' => 'users#show'
      get '' => 'users#show'
    end

    scope 'topics' do
      scope 'follows' do
        post '' => 'follows#create', :type => 'Topic'
        delete '' => 'follows#destroy', :type => 'Topic'
      end

      scope 'connections' do
        post '' => 'topic_connections#add'
        get '' => 'topic_connections#index'
        delete '' => 'topic_connections#remove'
      end

      scope 'aliases' do
        post '' => 'topics#add_alias'
        put '' => 'topics#update_alias'
        delete '' => 'topics#destroy_alias'
      end

      post 'update_image' => 'topics#update_image'
      get 'followers' => 'topics#followers'
      get 'suggestions' => 'topics#suggestions'
      get 'index' => 'topics#index'
      get 'categories' => 'topics#categories'
      get 'top_by_category' => 'topics#top_by_category'
      get 'for_connection' => 'topics#for_connection'

      scope ':id' do
        put 'freebase' => 'topics#update_freebase'
        delete 'freebase' => 'topics#delete_freebase'
        put 'categories' => 'topics#add_category'
        get 'children' => 'topics#children'
        get 'parents' => 'topics#parents'
        get '' => 'topics#show'
      end

      delete '' => 'topics#destroy'
      post '' => 'topics#create', :as => :topics
      put '' => 'topics#update'
      get '' => 'topics#index'
    end

    scope 'posts' do
      post '' => 'posts#create'
      get 'stream' => 'posts#stream'
      get 'user_feed' => 'posts#user_feed'
      get 'activity_feed' => 'posts#activity_feed'
      get 'topic_feed' => 'posts#topic_feed'
      get 'responses' => 'posts#responses'
      put 'disable' => 'posts#disable'
      delete 'mentions' => 'posts#delete_mention'
      post 'mentions' => 'posts#create_mention'
      post ':id/shares' => 'posts#publish_share'
      delete ':id/shares' => 'posts#discard_share'
      post ':id/publish' => 'posts#publish'
      delete ':id' => 'posts#destroy'
      get ':id' => 'posts#show'
      get '' => 'posts#index'
    end

    scope 'comments' do
      get '' => 'comments#index'
      post '' => 'comments#create'
      delete '' => 'comments#destroy'
    end

    scope 'invite_codes' do
      post 'check' => 'invite_codes#check'
    end

    scope 'beta_signups' do
      post '' => 'beta_signups#create'
    end

    get 'influence_increases' => 'users#influence_increases'
  end

  admin_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.role?('admin')
  end
  constraints admin_constraint do
    mount Sidekiq::Web, at: 'admin/workers'
  end

  mount Soulmate::Server, :at => "autocomplete"

  get 'testing' => 'testing#test', :as => :test

  get 'embed' => 'embedly#show', :as => :embedly_fetch

  devise_for :users, :skip => [:sessions], :controllers => { :omniauth_callbacks => "omniauth_callbacks",
                                           :registrations => :registrations,
                                           :confirmations => :confirmations,
                                           :sessions => :sessions }
  devise_scope :user do
    get '' => 'users#feed', :as => :new_user_session
    post 'sign_in' => 'sessions#create', :as => :user_session
    get 'sign_out' => 'sessions#destroy', :as => :destroy_user_session
  end
  get '/users/auth/:provider' => 'omniauth_callbacks#passthru'

  scope 'users' do
    get ':slug/users' => 'users#show', :as => :user_topics
    get ':slug/topics' => 'users#show', :as => :user_users
    get ':slug/feed' => 'users#show', :as => :user_feed
    get ':slug/:topic_id' => 'users#show', :as => :user_topic_activity
    get ':slug' => 'users#show', :as => :user, :show_og => true
  end
  get 'invited' => 'invite_codes#check', :as => :invited
  get 'settings' => 'users#settings', :as => :user_settings
  get 'activity/:topic_id' => 'users#show'
  get 'activity' => 'users#show'
  get 'users' => 'users#show'
  get 'topics' => 'users#show'
  get 'posts/new' => 'posts#new', :as => :new_post
  get 'posts/:id' => 'posts#show', :as => :post

  scope 'pages' do
    get 'about' => 'pages#about', :as => :about
    get 'contact' => 'pages#contact', :as => :contact
    get 'privacy' => 'pages#privacy', :as => :privacy
    get 'terms' => 'pages#terms', :as => :terms
    get 'help' => 'pages#help', :as => :help
    get 'bookmarklet' => 'pages#bookmarklet', :as => :bookmarklet
    scope 'admin' do
      get '' => 'pages#admin', :as => :admin, :require_admin => true
      get 'users/index' => 'users#show', :as => :user_index, :require_admin => true
      get 'users/new_stub' => 'users#show', :as => :new_stub_user, :require_admin => true
      get 'topics/duplicates' => 'topics#duplicates', :as => :admin_topic_duplicates
      get 'topics/for_connection' => 'users#show', :as => :topics_for_connection, :require_admin => true
      get 'posts/stream' => 'users#show', :as => :admin_post_stream, :require_admin => true
    end
  end

  resources :invite_codes, :only => [:create, :new]
  post '/invite_codes/check' => 'invite_codes#check', :as => :check_invite_code
  get '/contacts/:provider/callback' => 'users#show_contacts', :as => :show_contacts
  get '/contacts/failure' => 'users#contacts_failure', :as => :contacts_failure

  resources :crawler_sources

  get 'topics/new' => 'topics#new', :as => :new_topic
  get ':slug/users' => 'topics#show', :as => :topic_users
  get ':slug' => 'topics#show', :as => :topic #(catch all)

  root :to => 'users#feed'

end

app/models/crawler_source.rb
class CrawlerSource
  include Mongoid::Document

  field :source_name
  field :category
  field :url
  field :last_crawled
  field :last_modified
  field :etag
  field :posts_added, :default => 0
  field :status, :default => 'active'

  attr_accessible :source_name, :category, :url, :status

  validates :url, :uniqueness => { :case_sensitive => false, :message => 'URL is already in use!' }
end

app/controllers/crawler_sources_controller.rb
class CrawlerSourcesController < ApplicationController
  # GET /crawler_sources
  # GET /crawler_sources.json
  def index
    @crawler_sources = CrawlerSource.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @crawler_sources }
    end
  end

  # GET /crawler_sources/1
  # GET /crawler_sources/1.json
  def show
    @crawler_source = CrawlerSource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @crawler_source }
    end
  end

  # GET /crawler_sources/new
  # GET /crawler_sources/new.json
  def new
    @crawler_source = CrawlerSource.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @crawler_source }
    end
  end

  # GET /crawler_sources/1/edit
  def edit
    @crawler_source = CrawlerSource.find(params[:id])
  end

  # POST /crawler_sources
  # POST /crawler_sources.json
  def create
    @crawler_source = CrawlerSource.new(params[:crawler_source])

    respond_to do |format|
      if @crawler_source.save
        format.html { redirect_to @crawler_source, notice: 'Crawler source was successfully created.' }
        format.json { render json: @crawler_source, status: :created, location: @crawler_source }
      else
        format.html { render action: "new" }
        format.json { render json: @crawler_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /crawler_sources/1
  # PUT /crawler_sources/1.json
  def update
    @crawler_source = CrawlerSource.find(params[:id])

    respond_to do |format|
      if @crawler_source.update_attributes(params[:crawler_source])
        format.html { redirect_to @crawler_source, notice: 'Crawler source was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @crawler_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crawler_sources/1
  # DELETE /crawler_sources/1.json
  def destroy
    @crawler_source = CrawlerSource.find(params[:id])
    @crawler_source.destroy

    respond_to do |format|
      format.html { redirect_to crawler_sources_url }
      format.json { head :no_content }
    end
  end
end

app/views/crawler_sources/_form.html.erb
<%= form_for(@crawler_source) do |f| %>
  <% if @crawler_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crawler_source.errors.count, "error") %> prohibited this crawler_source from being saved:</h2>

      <ul>
      <% @crawler_source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :source_name %><br />
    <%= f.text_field :source_name %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crawler_sources/edit.html.erb
<h1>Editing crawler_source</h1>

<%= render 'form' %>

<%= link_to 'Show', @crawler_source %> |
<%= link_to 'Back', crawler_sources_path %>

app/views/crawler_sources/index.html.erb
<h1>Listing crawler_sources</h1>

<%= link_to 'New Crawler source', new_crawler_source_path %>

<table>
  <tr>
    <th>Source name</th>
    <th>Category</th>
    <th>Url</th>
    <th>Last crawled</th>
    <th>Last modified</th>
    <th>Posts added</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @crawler_sources.each do |crawler_source| %>
  <tr>
    <td><%= crawler_source.source_name %></td>
    <td><%= crawler_source.category %></td>
    <td><%= crawler_source.url %></td>
    <td><%= pretty_time(crawler_source.last_crawled) if crawler_source.last_crawled %></td>
    <td><%= pretty_time(crawler_source.last_modified) if crawler_source.last_modified %></td>
    <td><%= crawler_source.posts_added %></td>
    <td><%= crawler_source.status %></td>
    <td><%= link_to 'Show', crawler_source %></td>
    <td><%= link_to 'Edit', edit_crawler_source_path(crawler_source) %></td>
    <td><%= link_to 'Destroy', crawler_source, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/crawler_sources/new.html.erb
<h1>New crawler_source</h1>

<%= render 'form' %>

<%= link_to 'Back', crawler_sources_path %>

app/views/crawler_sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Source name:</b>
  <%= @crawler_source.source_name %>
</p>

<p>
  <b>Category:</b>
  <%= @crawler_source.category %>
</p>

<p>
  <b>Url:</b>
  <%= @crawler_source.url %>
</p>

<p>
  <b>Last crawled:</b>
  <%= @crawler_source.last_crawled %>
</p>

<p>
  <b>Last modified:</b>
  <%= @crawler_source.last_modified %>
</p>

<p>
  <b>Etag:</b>
  <%= @crawler_source.etag %>
</p>

<p>
  <b>Posts added:</b>
  <%= @crawler_source.posts_added %>
</p>

<p>
  <b>Status:</b>
  <%= @crawler_source.status %>
</p>


<%= link_to 'Edit', edit_crawler_source_path(@crawler_source) %> |
<%= link_to 'Back', crawler_sources_path %>